FROM python:slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONFAULTHANDLER=1
ENV PYTHONHASHSEED=random
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=1000

RUN apt update -y \
    && pip install -U pip \
    && pip install poetry

WORKDIR /dc-assignments

COPY poetry.lock pyproject.toml /dc-assignments/
COPY src /dc-assignments/src

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --without dev
