version: "3.9"

services:
  mmn-test:
    container_name: mmn-test
    build:
      context: .
      dockerfile: Dockerfile.slim
    command: python3 test/mmn.py --multiprocessing
    volumes:
      - ./:/dc-assignments
      - /etc/localtime:/etc/localtime:ro
    working_dir: /dc-assignments
    environment:
      - TZ=Europe/Rome
    restart: on-failure
  
  storage-test:
    container_name: storage-test
    build:
      context: .
      dockerfile: Dockerfile.slim
    command: python3 test/storage.py config/p2p.cfg --multiprocessing
    volumes:
      - ./:/dc-assignments
      - /etc/localtime:/etc/localtime:ro
    working_dir: /dc-assignments
    environment:
      - TZ=Europe/Rome
    restart: on-failure